index:
    path: /
    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login
reset:
    path: /reset
    controller: App\Controller\PasswordResetController::reset